### ISSUE TITLE
Forgot password 404

### ISSUE THREAD

**Issue by rodolfomartinez** [AcademicsToday/py-academicstoday#117]
Summary:
Using the Forgot password link in the login box gives a 404
![screenshot from 2015-04-27 16 25 19](https://cloud.githubusercontent.com/assets/7537946/7357009/03d493e4-ecfa-11e4-8351-cb0eda2b9e3a.png)

**Comment by bartmika** [comment]
This issue is a duplicate of issue #104. Once that issue is closed, this ticket will be closed too.
