### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by rodolfomartinez** [AcademicsToday/py-academicstoday#118]
Summary:
The current 404 page is kind of scary
![screenshot from 2015-04-27 16 25 19](https://cloud.githubusercontent.com/assets/7537946/7357022/0e544620-ecfa-11e4-9599-34a58265d995.png)

Consider creating a themed 404 page.

**Comment by bartmika** [comment]
Set DEBUG=False on broad so this scary message won't appear again.

(Note: Locally set DEBUG=True so we can diagnose problems.)
